//
// Created by kjeld on 31/01/2021.
//

#ifndef BURNT_WOOD_LAMP_CONFIGVARIABLES_H
#define BURNT_WOOD_LAMP_CONFIGVARIABLES_H

#define MAX_BRIGHTNESS 255
#define MAX_BRIGHTNESS_PER_CHANNEL 255
#define NUM_LEDS 100
#define NUM_LEDS_LOWER 50
#define NUM_LEDS_UPPER 50

#define CHIPSET WS2811
#define COLOR_ORDER GRB

#define DATA_PIN D5

#endif //BURNT_WOOD_LAMP_CONFIGVARIABLES_H
