//
// Created by kjeld on 31/01/2021.
//

#ifndef BURNT_WOOD_LAMP_CONFIGVARIABLES_H
#define BURNT_WOOD_LAMP_CONFIGVARIABLES_H

#define MAX_BRIGHTNESS 72
#define MAX_BRIGHTNESS_PER_CHANNEL 24
#define NUM_LEDS 109
#define NUM_LEDS_LOWER 55
#define NUM_LEDS_UPPER 54

#define CHIPSET WS2812
#define COLOR_ORDER GRB

#define DATA_PIN D5

#endif //BURNT_WOOD_LAMP_CONFIGVARIABLES_H
